### ISSUE TITLE
is there any "Naming rules" in ros1_bridge when using custom msg ?

### ISSUE THREAD

**Issue by lxbeyond** [ros2/ros1_bridge#114]
I want communicate between ros1 and ros2 using custom msg with the help of ros1_bridge, but I was stick to building msg,  I build package called "zoro_msg", however  "ros2 run ros1_bridge dynamic_bridge --print-pairs" command did't display the "zoro_msg", and talker could't pass data to listener through ros bridge. and I try a lot, lastly I changed package name from "zoro_msg" to "zoro_msgs", and then it worked , but I got confused and didn't know why . could anybody tell me why ?
the code is in : https://github.com/lxbeyond/ros1_bridge_msg.git

**Comment by mikaelarguedas** [comment]
Yes currently the automatic matching of the message packages is done only for packages ending with `_msgs`.
From the [documentation](https://github.com/ros2/ros1_bridge/blob/f8a6b6dce79937380b341d943d667ccde5287e5e/doc/index.rst#how-are-ros-1-and-2-messages-associated-with-each-other): "In the first step ROS 1 packages ending with `_msgs` are associated with ROS 2 packages ending in either `_msgs` or `_interfaces`"

IDK if this is a rule that will be made more flexible in the future, maybe @dirk-thomas has more context here

**Comment by dirk-thomas** [comment]
I assume the actual question has been answered already and the documentation states the matching heuristic as well as how to define custom mappings. Therefore I will go ahead and close this for now.
