### ISSUE TITLE
--print-pairs prints only messages and not services

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros1_bridge#115]
I think it's a bug but maybe this is on purpose ?

**Comment by dhood** [comment]
Labelled this as a "good first issue" so I will give some additional context (if any contributors are interested in picking this up please say so).

The task is a followup of https://github.com/ros2/ros1_bridge/pull/59/files, to include a function to get all service mappings as well.
The services are stored in a python variable `services` that will need to be passed into the EmPy template [here](https://github.com/ros2/ros1_bridge/blob/ca304946831916945c047ee37481a2ee2ad931a6/ros1_bridge/__init__.py#L90).
[This template](https://github.com/ros2/ros1_bridge/blob/5c14d9e35b07b35820ad7df1df853b4a7bbad3ca/resource/pkg_factories.cpp.em#L275) has example usage of the `services` variable.
