### ISSUE TITLE
ROS 2 port of Gazebo Msgs incompatible with ROS 1 bridge.

### ISSUE THREAD

**Issue by crdelsey** [ros2/ros1_bridge#128]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - Kinetic from binary, ROS 2 from source, release latest tag (Bouncy)
- Version or commit hash:
  - Bouncy
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
Gazebo msgs has recently been ported to ROS 2. Rebuilding the ros1_bridge with that repo present results in a compilation failure.
```
libros1_bridge.so: undefined reference to `ros1_bridge::Factory<gazebo_msgs::ODEJointProperties_<std::allocator<void> >, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > >::convert_1_to_2(gazebo_msgs::ODEJointProperties_<std::allocator<void> > const&, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> >&)'
libros1_bridge.so: undefined reference to `ros1_bridge::Factory<gazebo_msgs::ODEJointProperties_<std::allocator<void> >, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > >::convert_2_to_1(gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > const&, gazebo_msgs::ODEJointProperties_<std::allocator<void> >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [static_bridge] Error 1
make[1]: *** [CMakeFiles/static_bridge.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libros1_bridge.so: undefined reference to `ros1_bridge::Factory<gazebo_msgs::ODEJointProperties_<std::allocator<void> >, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > >::convert_1_to_2(gazebo_msgs::ODEJointProperties_<std::allocator<void> > const&, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> >&)'
libros1_bridge.so: undefined reference to `ros1_bridge::Factory<gazebo_msgs::ODEJointProperties_<std::allocator<void> >, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > >::convert_2_to_1(gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > const&, gazebo_msgs::ODEJointProperties_<std::allocator<void> >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [parameter_bridge] Error 1
make[1]: *** [CMakeFiles/parameter_bridge.dir/all] Error 2
libros1_bridge.so: undefined reference to `ros1_bridge::Factory<gazebo_msgs::ODEJointProperties_<std::allocator<void> >, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > >::convert_1_to_2(gazebo_msgs::ODEJointProperties_<std::allocator<void> > const&, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> >&)'
libros1_bridge.so: undefined reference to `ros1_bridge::Factory<gazebo_msgs::ODEJointProperties_<std::allocator<void> >, gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > >::convert_2_to_1(gazebo_msgs::msg::ODEJointProperties_<std::allocator<void> > const&, gazebo_msgs::ODEJointProperties_<std::allocator<void> >&)'
collect2: error: ld returned 1 exit status
```

#### Additional information

The error only affects the ODEJointProperties message. This is because 2 of the fields had to be renamed due to the new ROS 2 naming conventions. The original version used camelCase names for hiStop and loStop fields. This is disallowed by the ROS 2 msg file processor.

Because of the name mismatch, I believe the ros1_bridge code generator doesn't consider the ODEJointProperties in Kinetic a match and doesn't generate code.

Unfortunately, the ODEJointProperties message is referred to from the SetJointProperties service which the ros1_bridge does generate code for. This results in the undefined reference above.

**Comment by dirk-thomas** [comment]
Please fill a ticket in the corresponding repository instead (https://github.com/ros-simulation/gazebo_ros_pkgs). If the message definition has been changed the package should provide the appropriate mapping rule as described in the [docs](https://github.com/ros2/ros1_bridge/blob/master/doc/index.rst).

Please reference this ticket from the new ticket (or vice versa) so that future reader will find the follow up ticket.
