### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by math4356** [ros2/ros1_bridge#142]
```

```

#### Actual behavior
Starting >>> ros1_bridge
[Processing: ros1_bridge]                             
--- stderr: ros1_bridge                               
CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target test_ros2_server_cpp
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:171 (custom_executable)

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target test_ros2_client_cpp
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:169 (custom_executable)

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target dynamic_bridge
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:161 (custom_executable)

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target simple_bridge_1_to_2
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:120 (custom_executable)

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target static_bridge because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:147 (custom_executable)

CMake Warning at CMakeLists.txt:131 (add_library):
  Cannot generate a safe runtime search path for target ros1_bridge because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target simple_bridge_2_to_1
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:123 (custom_executable)

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target simple_bridge because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:127 (custom_executable)

CMake Warning at CMakeLists.txt:102 (add_executable):
  Cannot generate a safe runtime search path for target parameter_bridge
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libconsole_bridge.so.0.4] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/ros/bouncy/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:154 (custom_executable)

In file included from /home/xuchang/chang_ws/ros1_bridge/build/ros1_bridge/generated/get_factory.cpp:3:0:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp: In static member function ‘static void ros1_bridge::Factory<ROS1_T, ROS2_T>::ros2_callback(typename ROS2_T::SharedPtr, const rmw_message_info_t&, ros::Publisher, const string&, const string&, rclcpp::PublisherBase::SharedPtr)’:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp:166:85: error: request for member ‘str’ in ‘rcutils_get_error_string()’, which is of non-class type ‘const char*’
         auto msg = std::string("Failed to compare gids: ") + rmw_get_error_string().str;
                                                                                     ^~~
In file included from /home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/builtin_interfaces_factories.hpp:29:0,
                 from /home/xuchang/chang_ws/ros1_bridge/ros1_bridge/src/builtin_interfaces_factories.cpp:21:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp: In static member function ‘static void ros1_bridge::Factory<ROS1_T, ROS2_T>::ros2_callback(typename ROS2_T::SharedPtr, const rmw_message_info_t&, ros::Publisher, const string&, const string&, rclcpp::PublisherBase::SharedPtr)’:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp:166:85: error: request for member ‘str’ in ‘rcutils_get_error_string()’, which is of non-class type ‘const char*’
 uto msg = std::string("Failed to compare gids: ") + rmw_get_error_string().str;
                                                                            ^~~
make[2]: *** [CMakeFiles/ros1_bridge.dir/generated/get_factory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/xuchang/chang_ws/ros1_bridge/build/ros1_bridge/generated/actionlib_msgs_factories.hpp:3:0,
                 from /home/xuchang/chang_ws/ros1_bridge/build/ros1_bridge/generated/actionlib_msgs_factories.cpp:4:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp: In static member function ‘static void ros1_bridge::Factory<ROS1_T, ROS2_T>::ros2_callback(typename ROS2_T::SharedPtr, const rmw_message_info_t&, ros::Publisher, const string&, const string&, rclcpp::PublisherBase::SharedPtr)’:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp:166:85: error: request for member ‘str’ in ‘rcutils_get_error_string()’, which is of non-class type ‘const char*’
         auto msg = std::string("Failed to compare gids: ") + rmw_get_error_string().str;
                                                                                     ^~~
In file included from /home/xuchang/chang_ws/ros1_bridge/build/ros1_bridge/generated/cartographer_ros_msgs_factories.hpp:3:0,
                 from /home/xuchang/chang_ws/ros1_bridge/build/ros1_bridge/generated/cartographer_ros_msgs_factories.cpp:4:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp: In static member function ‘static void ros1_bridge::Factory<ROS1_T, ROS2_T>::ros2_callback(typename ROS2_T::SharedPtr, const rmw_message_info_t&, ros::Publisher, const string&, const string&, rclcpp::PublisherBase::SharedPtr)’:
/home/xuchang/chang_ws/ros1_bridge/ros1_bridge/include/ros1_bridge/factory.hpp:166:85: error: request for member ‘str’ in ‘rcutils_get_error_string()’, which is of non-class type ‘const char*’
         auto msg = std::string("Failed to compare gids: ") + rmw_get_error_string().str;
                                                                                     ^~~
make[2]: *** [CMakeFiles/ros1_bridge.dir/generated/cartographer_ros_msgs_factories.cpp.o] Error 1
make[2]: *** [CMakeFiles/ros1_bridge.dir/src/builtin_interfaces_factories.cpp.o] Error 1
make[2]: *** [CMakeFiles/ros1_bridge.dir/generated/actionlib_msgs_factories.cpp.o] Error 1
make[1]: *** [CMakeFiles/ros1_bridge.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< ros1_bridge	[ Exited with code 2 ]

Summary: 0 packages finished [32.3s]
  1 package failed: ros1_bridge
  1 package had stderr output: ros1_bridge

#### Additional information
Hello, when I built ros1_bridge package, these errors just appeared. Anyone knows how to figure out?

Thanks !!!

The following are my source commands

source /opt/ros/melodic/setup.bash
source /opt/ros/bouncy/setup.bash

**Comment by clalancette** [comment]
Did you follow the instructions exactly in https://github.com/ros2/ros1_bridge/blob/master/README.md ?  It is very important to get the bridge to build.

In general, please ask these types of questions on https://answers.ros.org .  That keeps all of the questions in a single place and allows other people to more easily find them.  I'm going to close this out for now, but if you are still having problems, please open a new question over on answers.  Thanks.
