### ISSUE TITLE
ros1_bridge/__init__.py: potential error in determine_package_pairs

### ISSUE THREAD

**Issue by cyrilleberger** [ros2/ros1_bridge#150]
Probably not a bug, but I was trying to figure out why  my mapping didn't work, and in doing so I stumbled upon the following suspicious line:

https://github.com/ros2/ros1_bridge/blob/d0c15515633f85266ac562de607ad773bcb8aed6/ros1_bridge/__init__.py#L444

is_package_mapping is a function, and I suspect the intent for that line was to call the function and not check if the function exists.

**Comment by dirk-thomas** [comment]
Thanks for reporting this. It certainly looks wrong. See #151 for the fix.
