### ISSUE TITLE
Failed to connect to 10.8.0.1:XXXXXX

### ISSUE THREAD

**Issue by RDaneelOlivav** [ros2/ros1_bridge#155]
Hi, 
I'm launching ros1bridge in crystal and it works great! But for some reason when killing gazebo simulator and launching a new simulator, it starts to print the message "Failed to connect to 10.8.0.1:XXXXXX". It's still working, taking services and topics, its just now printing those kinds of messages Even if I just kill it and relaunch again the commands:

    export ROS_MASTER_URI=http://localhost:11311
    ros2 run ros1_bridge dynamic_bridge

Any Ideas of what it might be causing this? What function have those ports 10.8.0.1:XXXXXX in ros1bridge?

Thanks

**Comment by dirk-thomas** [comment]
Closing due to no response. Please feel free to comment on the closed ticket with the requested information and the issue can be reopened if necessary.
