### ISSUE TITLE
ros-crystal-gazebo-msgs

### ISSUE THREAD

**Issue by RDaneelOlivav** [ros2/ros1_bridge#156]
The debian version of ros1-bridge just released for crystal seems to not support gazebo_msgs. When launching ros1-bridge installed from the repo, only finds gazebo services that are from std_srvs package, so it seems it wasn't compiled with gazebo_msgs.

I reffer to the connection with Gazebo using ROS1. I know that the GAzebo version for ROS2 supports this, but in that case ros1-bridge is irrelevant.

Is there any plan for a later release with that support in mind?

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem. Fixed in the latest release: ros2/rosdistro#491
