### ISSUE TITLE
Dynamic bridge only works if mapping rule is created between two packages with same naming, messages and message fields

### ISSUE THREAD

**Issue by TSC21** [ros2/ros1_bridge#157]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Form source
- Version or commit hash:
  - `bouncy` branch
- DDS implementation:
  - Fast RTPS

#### Steps to reproduce issue
Follow the steps set in:
1. https://dev.px4.io/en/middleware/micrortps.html#setting-up-the-workspaces
2. https://dev.px4.io/en/middleware/micrortps.html#building-the-workspaces
3. https://dev.px4.io/en/middleware/micrortps.html#testing-the-px4-fastrpts-bridge-with-ros2-and-ros

Basically, the steps above configure two workspaces, one for ROS2, which contains `ros1_bridge`, and one for ROS1. All the messages for both ROS2 and ROS1 are generated on build time and `ros1_bridge` is built after all these messages, with respective headers and sources, are generated.

#### Expected behavior
It's expected that the dynamic bridge would work without the need of adding mapping rules between the packages on the ROS2 and the ROS1 side, given that the package, message naming and fields are exactly the same.

#### Actual behavior
The bridging only happens if a mapping rules yaml file is added: https://github.com/PX4/px4_ros_com/blob/master/px4_ros_com_mapping_rules.yaml.
After I launch the dynamic bridge, I launch a ROS1 listener node for one the msgs being propagated in the stream (`SensorCombined`), in order to listen to the msgs coming from the ROS2 side. I don't get any data, but I do find that in the console where I have launched the dynamic_bridge, it appears the following:

```sh
failed to create 2to1 bridge for topic '/SensorCombined_topic' with ROS 2 type 'px4_ros_com/SensorCombined' and ROS 1 type '': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option
```

This, in the other hand, does not happen if I add the mapping rule. This is still not pretty, because even though it creates the bridge between topics, we can see that it's not a clean bridge, since it appears on the same console where I launch the `ros1_bridge` dynamic bridge:

```sh
created 2to1 bridge for topic '/SensorCombined_topic' with ROS 2 type 'px4_ros_com/SensorCombined' and ROS 1 type ''
```

where I was expecting:

```sh
created 2to1 bridge for topic '/SensorCombined_topic' with ROS 2 type 'px4_ros_com/SensorCombined' and ROS 1 type 'px4_ros_com/SensorCombined'.
```

#### Additional information

The source code is available at https://github.com/PX4/px4_ros_com.

Thanks in advance for this!

**Comment by TSC21** [comment]
@nuclearsandwich any input here? Thanks!

**Comment by dirk-thomas** [comment]
The heuristic for matching messages types between ROS 1 and ROS 2 is documented here: https://github.com/ros2/ros1_bridge/blob/master/doc/index.rst

On a first look out seems that your package doesn't end in `_msgs` and therefore isn't being considered by the heuristic. That would also be the reason that it works with a trivial 1-to-1 mapping rule.

**Comment by TSC21** [comment]
> On a first look out seems that your package doesn't end in _msgs and therefore isn't being considered by the heuristic.

Seems like I missed that. Thanks for the tip @dirk-thomas! I will try to build the messages in a separate package with the proper naming and will let you know if it worked.

**Comment by dirk-thomas** [comment]
@TSC21 Any update on this?

**Comment by dirk-thomas** [comment]
Since there was no further update I will go ahead and close this ticket for now since the behavior is exactly as documented. Please feel free to continue commenting and the ticket can be reopened if necessary.

**Comment by nickolai-voyage** [comment]
I also had trouble with this, but was ultimately able to build a successful test project which I've uploaded at https://github.com/voyage/ros1_bridge_test.
