### ISSUE TITLE
Failed to get response from ROS service runtime_error should be informative

### ISSUE THREAD

**Issue by tomasruizt** [ros2/ros1_bridge#166]
## Feature request
runtime_error should be informative.
#### Expected behavior
`"what(): Failed to get response from ROS service: myservice/"`
#### Actual behavior
`"what(): Failed to get response from ROS service"`

#### Implementation considerations
Change the code in:
https://github.com/ros2/ros1_bridge/blob/961ddee6b76bcb670ce3cb939d125044de820102/include/ros1_bridge/factory.hpp#L252
to 
```cpp
throw std::runtime_error("Failed to get response from ROS service: " + client.getService());
```
### Optional
Maybe it should include the fact that the error was thrown from the `ros1_bridge`

**Comment by dirk-thomas** [comment]
Please consider to create a pull request with your proposed patch.
