### ISSUE TITLE
Supporting bridging based on topic name and message name

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros1_bridge#2]
The supported message types will be limited to the message definitions available at compile time of the bridge.

* [x] Support using the message name instead of the message type: b41b472b7b4f18257196e16de342ccc4e8f870ba
* [x] Generate type support for all available messages: d0ee70e25555ac573a1b918d923f59008dad6e98

**Comment by dirk-thomas** [comment]
Please review the referenced commits.

**Comment by wjwwood** [comment]
+1
