### ISSUE TITLE
Problems with ros1_bridge static_bridge "No template specialization for the pair"

### ISSUE THREAD

**Issue by zxc455233** [ros2/ros1_bridge#208]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04, ROS2 Dashing
- Installation type:
  - from source
- Version or commit hash:
  - 
- DDS implementation:
  - RTI Connext
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```
# Shell 1
$ source /opt/ros/melodic/setup.bash
$ roscore &
$ rosrun rospy_tutorials talker

# Shell 2
# I built the ros1_bridge in ros2_ws
$ source ros2_ws/install/setup.bash
$ ros2 run ros1_bridge static_bridge
[INFO] [ros_bridge]: create bidirectional bridge for topic chatter
terminate called after throwing an instance of 'std::runtime_error'
  what():  No template specialization for the pair
```

#### Expected behavior
I want to bridge the specific topic to ROS2, but it doesn't work on tutorial's talker

----
## Feature request
Filters for bridge specific topic or except some topics

#### Feature description

I want to use ros1_bridge to communicate between multi-robots which based on ROS1 through DDS
But there is a problem with bridging **big data** like image_raw when I use dynamic_bridge --bridge-all-topics
It will cause the network traffic jams

Is it possible to filter some topics or make a rule file to bridge topics that I wanted?

**Comment by dirk-thomas** [comment]
Thank you for reporting this. #209 fixes the `static_bridge`.

The static bridge is a demonstration how a single topic with a specific type can be bridged. You could implement your own static bridge for you specific topic types / names - all you need to change from the example are these few lines: https://github.com/ros2/ros1_bridge/blob/ceed503ff26291e7e0a27225e002ccd5bd5b1dc7/src/static_bridge.cpp#L43-L46
