### ISSUE TITLE
Unable to create a template for a custom message

### ISSUE THREAD

**Issue by Mavahu** [ros2/ros1_bridge#271]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - ros1(binaries), ros2(binaries), ros1_bridge(source)
- Version or commit hash:
  - eloquent
- DDS implementation:
  - standard?

#### Steps to reproduce issue
- Extract the following nodes [ros 1,2 nodes.zip](https://github.com/ros2/ros1_bridge/files/4736581/ros.1.2.nodes.zip)
- Build each node
- Checkout ros1_bridge -b eloquent
- Run following commands:
`. /opt/ros/melodic/setup.bash`
`. /opt/ros/crystal/setup.bash`
`. <workspace-parent-path>/ros1_msgs_ws/install_isolated/setup.bash`
`. <workspace-parent-path>/ros2_msgs_ws/install/local_setup.bash`
`cd <workspace-parent-path>/bridge_ws`
`colcon build --packages-select ros1_bridge --cmake-force-configure`
`ros2 run ros1_bridge dynamic_bridge --print-pairs`

#### Expected behavior
A template for my custom message.
#### Actual behavior
No template appears.

**Comment by dirk-thomas** [comment]
Please read the documentation how to add your own message mappings: https://github.com/ros2/ros1_bridge/blob/master/doc/index.rst

* the part about the package names automatically considered (which yours doesn't match)
* how to provide custom mapping rules (which your package doesn't have atm)
