### ISSUE TITLE
Ros Kinetic

### ISSUE THREAD

**Issue by Schloern93** [ros2/ros1_bridge#289]
Hallo,

I hope I am asking this question in the right place.
Is this bridge also working for Ros Kinetic on Ubuntu 16.04 to Ros dashing on Ubuntu 18.04?
Best regards 

Florian Ehnle

**Comment by clalancette** [comment]
Please ask these kinds of questions on https://answers.ros.org.  That way, we have a single place where questions and answers are recorded and can be searched.

I'm going to close this out, but please feel free to keep commenting.
