### ISSUE TITLE
Error buiding ros1 bridge

### ISSUE THREAD

**Issue by Schloern93** [ros2/ros1_bridge#290]
Hello together,

System Ubuntu 18.04
Ros Environment
1. Ros dashing 
2. Ros melodic

The following are the steps I have tried

1. Get ros2_bridge with git clone into my ros2 dashing workspace
2. source ros2 dashing environment
3. build workspace without the ros1_bridge 
                     colcon build --symlink-install --packages-skip ros1_bridge
4. source ros1 melodic environment in the same terminal
5. source ros2 dashing workspace 
6 build the ros1_bridge 
                      colcon build --symlink-install --packages-select ros1_bridge --cmake-               force-configure

Error message was attached to the message.

The Error:
/home/florian/ros2_platform/ros2_ws/src/ros1_bridge/test/test_ros2_client.cpp:37:13: error: ‘rclcpp::FutureReturnCode’ has not been declared
     rclcpp::FutureReturnCode::SUCCESS)

Is it possible that the code is too new for ros dashing?

Thanks in advance
[error_ building_ros1_bridge.txt](https://github.com/ros2/ros1_bridge/files/5509318/error_.building_ros1_bridge.txt)

**Comment by clalancette** [comment]
Yes, if you are building against Dashing, you have to use the `dashing` branch of `ros1_bridge`.  Can you please try that and report back?

**Comment by Schloern93** [comment]
Thanks for the quick response.
I can build the package now. But I still get an error. File was attached.
But I can run the examples without errors.

[error_ building_ros1_bridge.txt](https://github.com/ros2/ros1_bridge/files/5517438/error_.building_ros1_bridge.txt)

**Comment by clalancette** [comment]
Interesting, not sure why you are getting those warnings.  We are overlaying urdfdom libraries on top of the system ones, so that may be why CMake is complaining.

But in any case, those don't look like fatal warnings, and as you say your examples are working.  So I'm going to go ahead and close this out for now.
