### ISSUE TITLE
Ros bridge does not translate service messages

### ISSUE THREAD

**Issue by Schloern93** [ros2/ros1_bridge#291]
Hallo,

i have created a Ros1 service and a Ros2 service according to the following instructions
Ros1:
http://wiki.ros.org/ROS/Tutorials/WritingServiceClient%28c%2B%2B%29
Ros2:
https://index.ros.org/doc/ros2/Tutorials/Writing-A-Simple-Cpp-Service-And-Client/

I have now built the bridge in a separate package as follows.
1. source Ros2 environment
2. source Ros1 environment
4 Source Service package ros1
5. source service package ros2
6. building the Ros bridge in the separate package
Then I started the Ros bridge as described in the manual. For the examples of the subscriber and the publisher the bridge works.
But if I start the service over Ros1 and the client over Ros 2 I can't receive any messages. 
I have attached screenshots of the terminals for starting the bridge and the service
Did I do something wrong when I built the bridge?
Many thanks in advance

Translated with www.DeepL.com/Translator (free version)
![Screenshot from 2020-11-11 10-53-38](https://user-images.githubusercontent.com/71652280/98803190-aa4c3900-2414-11eb-8e30-c699a97b80b7.png)
![Screenshot from 2020-11-11 10-53-41](https://user-images.githubusercontent.com/71652280/98803194-ac15fc80-2414-11eb-8b57-518903f2a73e.png)
![Screenshot from 2020-11-11 10-53-44](https://user-images.githubusercontent.com/71652280/98803207-ae785680-2414-11eb-9533-f53694d62bb0.png)
![Screenshot from 2020-11-11 10-53-48](https://user-images.githubusercontent.com/71652280/98803211-b0dab080-2414-11eb-8aec-fb61e67fa26d.png)

**Comment by iuhilnehc-ynos** [comment]
@Schloern93 


Please make sure checking the `pairs` information will show the following message

```
$ ros2 run ros1_bridge dynamic_bridge --print-pairs | grep begin
  - 'example_interfaces/srv/AddTwoInts' (ROS 2) <=> 'beginner_tutorials/AddTwoInts' (ROS 1)
```

> Did I do something wrong when I built the bridge?

Yes, I think that you could rebuild [example_interfaces](https://github.com/ros2/example_interfaces) after appending a mapping rule for your test into [mapping_rules.yaml](https://github.com/ros2/example_interfaces/blob/34f11b205aa2f5b79abe17d9c561ce53291128b3/mapping_rules.yaml)

```
-
  ros1_package_name: 'beginner_tutorials'
  ros1_service_name: 'AddTwoInts'
  ros2_package_name: 'example_interfaces'
  ros2_service_name: 'AddTwoInts'
```

**Comment by Schloern93** [comment]
I solved the problem. 
The problem was that I had built the ros1 workspace on kinetic. After I rebuilt it with melodic and built the ros_bridge it worked. 
The bridge now translates the messages to the ros kinetic workspace on my resberry pi.

**Comment by supergirl-os** [comment]
I built the ros_bridge on noetic, but it appears the same problem like you. I wonder if this is because the wrong vesion of ros. Or could you please tell me exactly how you solved this problem?
