### ISSUE TITLE
find_ros1_package() failed to find 'custom_msgs' using pkg_check_modules() 

### ISSUE THREAD

**Issue by chowkamlee81** [ros2/ros1_bridge#308]
After giving colcon build --packages-select ros1_bridge --cmake-force-configure --cmake-args -DBUILD_TESTING=FALSE
KIndly help
iam getting error below:

Starting >>> ros1_bridge
--- stderr: ros1_bridge
CMake Error at cmake/find_ros1_package.cmake:29 (message):
find_ros1_package() failed to find 'custom_msgs' using pkg_check_modules()
Call Stack (most recent call first):
CMakeLists.txt:53 (find_ros1_package)

Ki

**Comment by clalancette** [comment]
Please ask questions like this on https://answers.ros.org .  That is a our central location for questions and answers.  Also be sure to give a lot more detail about what operating system you are using, which ROS distribution you are using, what packages you are trying to build, and what commands you are running.
