### ISSUE TITLE
ros2 RMF messages to ros1

### ISSUE THREAD

**Issue by destkk** [ros2/ros1_bridge#312]
Operating System: Ubuntu 20.04

Hi there. I would like to check if there is anyone who has successfully build ros1_bridge with ros2 RMF messages.

I am trying to include RMF messages to be bridge over to ROS1 using this bridge. Apparently it is not part of the default messages that ros1_bridge could use. 

Appreciate if anyone could help me on this.

Thank you.

**Comment by clalancette** [comment]
I think the fact that nobody has commented on this in over 6 months is a good answer :).  In the future, please open questions like this on https://answers.ros.org, which is our central question-and-answer site.  I'm going to close this one out.
