### ISSUE TITLE
Colcon build failed

### ISSUE THREAD

**Issue by larsvlent** [ros2/ros1_bridge#319]
## Bug report

**Required Info:**

- Operating System:
  - 
  - Ubuntu 16.04
- Installation type:
  - 
  - source
- Version or commit hash:
  - 
  - ROS1: melodic & ROS2: Dashing & ros1_bridge: pulled 10-06-2021
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```
source /opt/ros/dashing/setup.bash
source /opt/ros/melodic/setup.bash
. ~/dev_ws/install/local_setup.bash
. ~/catkin_ws/devel/setup.bash
```

#### Expected behavior
A successful build
#### Actual behavior
Colcon build failed:
`
[Processing: ros1_bridge]                                            
--- stderr: ros1_bridge                                              
CMake Warning at CMakeLists.txt:171 (add_library):
  Cannot generate a safe runtime search path for target ros1_bridge because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [liburdfdom_sensor.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model_state.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_world.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib

  Some of these libraries may not be found correctly.

CMake Warning at CMakeLists.txt:142 (add_executable):
  Cannot generate a safe runtime search path for target static_bridge because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [liburdfdom_sensor.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model_state.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_world.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:188 (custom_executable)

CMake Warning at CMakeLists.txt:142 (add_executable):
  Cannot generate a safe runtime search path for target parameter_bridge
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [liburdfdom_sensor.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model_state.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_world.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:195 (custom_executable)

CMake Warning at CMakeLists.txt:142 (add_executable):
  Cannot generate a safe runtime search path for target dynamic_bridge
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [liburdfdom_sensor.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model_state.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_model.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib
    runtime library [liburdfdom_world.so.1.0] in /usr/lib/aarch64-linux-gnu may be hidden by files in:
      /opt/ros/dashing/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:202 (custom_executable)

---
Finished <<< ros1_bridge [19min 34s]
                            
Summary: 1 package finished [19min 35s]
  1 package had stderr output: ros1_bridge

`
#### Additional information
Please help me, how do I fix this?
----

**Comment by clalancette** [comment]
This is a question best asked on https://answers.ros.org.  That is our central resource for questions and answers, so we have a single searchable place.  I'm going to close this one out.
