### ISSUE TITLE
sensor_msgs::PointCloud2 message freeze

### ISSUE THREAD

**Issue by Thomas-Merlet** [ros2/ros1_bridge#332]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 18.04 LTS
- Installation type:
  -  Installed using binaries `sudo apt install ros-dashing-ros1-bridge`
- Version or commit hash:
  -  0.7.9-1bionic.20210521.231308
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

I'm using ROS 1 Melodic and ROS 2 Dashing. 

1. Play a bag file with sensor_msgs::PointCloud2 data in ROS1
2. Launch the bridge using `ros2 run ros1_bridge dynamic_bridge`
3. Launch multiple ROS1 nodes (like Autoware.IA ROS 1 nodes for example)
4. Launch a ROS2 nodes that subscribe to the raw sensor_msgs::PointCloud2 rosbag data

#### Expected behavior

No freeze in sensor_msgs::PointCloud2 messages.

#### Actual behavior

sensor_msgs::PointCloud2 messages freeze about every 2 seconds as shown below:

https://user-images.githubusercontent.com/26826861/137718233-bd4af98b-e956-498f-97b0-51852f518b22.mp4

#### Additional information

This seems to happen when multiple ROS 1 nodes are running. Stopping the ROS 1 nodes solve the issue. 

`top` gives the following output:
![Screenshot from 2021-10-18 11-44-39](https://user-images.githubusercontent.com/26826861/137718159-929b9fde-5a21-4f50-baae-a17da05a8342.png)

**Comment by clalancette** [comment]
Dashing is end-of-life now, so we are no longer doing updates or support for it.  I'll encourage you to use a newer distribution (Foxy or Galactic are still supported), and try again.

If you are still having problems, please open questions like these on https://answers.ros.org, which is our central question-and-answer place.
