### ISSUE TITLE
Feature Request: Allow Custom ROS1 and ROS2 Node Names

### ISSUE THREAD

**Issue by civerachb-cpr** [ros2/ros1_bridge#333]
#### Feature description
Add additional command-line arguments to allow specifying the ROS1 and ROS2 node names

Currently the name of the ROS1 and ROS2 nodes for the dynamic_bridge are hard-coded to `ros_bridge`.  This means it is impossible to have multiple bridges running concurrently, as the ROS1 nodes will clobber each other.  This prevents the use case where you have multiple ROS2 domains and want them all bridged together onto a single ROS1 master.

Adding the ability to specify the node name (e.g `ros2 run ros1_bridge dynamic_bridge --bridge-all-topics --ros1-node ros_bridge_domain_1`) would alleviate this problem.

For my current use-case I only need to be able to rename the ROS1 node, but there may be additional use-cases where renaming the ROS2 node would also be desirable.

#### Implementation considerations
The current `ros_bridge` default values can be preserved if the new arguments are omitted.  Modifying `parse_command_options` in `dynamic_bridge.cpp` should suffice.

It's likely desirable to add this feature to the other bridge classes (e.g. parameter_bridge).

**Comment by clalancette** [comment]
The original request here, to be able to remap the ROS 1 and ROS 2 names, seems to have been taken care of by https://github.com/ros2/ros1_bridge/issues/333#issuecomment-951001532 .  There is still an issue that has to do with renaming the ROS 1 and ROS 2 nodes differently, but that is not specific to this repository and doesn't seem to be a problem for the original reporter.  Given that, I'm actually going to close this out.  But feel free to reopen or keep commenting if you'd like to continue the conversation.
