### ISSUE TITLE
Param_Bridge cant parse --ros-args

### ISSUE THREAD

**Issue by geoeo** [ros2/ros1_bridge#375]
```
ros2 run ros1_bridge dynamic_bridge --ros-args -r __ns:=/test 
```

Works

```
ros2 run ros1_bridge parameter_bridge --ros-args -r __ns:=/test 
```

Crashes. This is a big problem when trying to launch from a launchfile

**Comment by gbiggs** [comment]
Please provide specific error output from the crash and as much detail about your environment as possible.

**Comment by geoeo** [comment]
- System : Ubuntu 20.04
- ROS2: Galatic
- Installation Type: From Apt

The error after running `ros2 run ros1_bridge parameter_bridge --ros-args -r __ns:=/test ` 

```
[ERROR] [1660892133.744271987] [rcl]: Failed to parse global arguments
terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'
  what():  failed to initialize rcl: Couldn't parse trailing -r flag. No remap rule found., at /tmp/binarydeb/ros-galactic-rcl-3.1.3/src/rcl/arguments.c:37
  ```
  
  I think this was already posted a year ago https://github.com/ros2/ros1_bridge/issues/316

**Comment by clalancette** [comment]
Yes, agreed, that is the same error as in #316.  Closing this as a duplicate.
