### ISSUE TITLE
Bridges to ROS 2 publishers/subscribers not removed when using Fast RTPS

### ISSUE THREAD

**Issue by dhood** [ros2/ros1_bridge#38]
Connects to ros2/rmw_fastrtps#64 - opening this ticket here for visibility.

Bridges aren't always removed when expected (when ROS 2 nodes shut down) if `rmw_fastrtps_cpp` is used as the rmw implementation

**Comment by Kukanani** [comment]
I just confirmed that this is still an issue, at least when the publishing ROS2 node is killed via Ctrl-C.

**Comment by Karsten1987** [comment]
The same goes for count subscriber / count publisher btw

**Comment by dirk-thomas** [comment]
@Kukanani @Karsten1987 have you both used the latest version from the default branches (including FastRTPS and rmw_fastrtps_cpp)?

**Comment by Kukanani** [comment]
Updating appears to have fixed the issue on my machine.

**Comment by Karsten1987** [comment]
bridge works for me. The output of "--show-introspection" shows that the ros2 node correctly disappears.

**Comment by dirk-thomas** [comment]
Based on the latest reports confirming that the current state works I will close this ticket for now. Please feel free to comment here if you still experience the problem and the ticket can be reopened.
