### ISSUE TITLE
No template specialization for the pair

### ISSUE THREAD

**Issue by mertbacaksiz** [ros2/ros1_bridge#394]
I use neotic as Ros1 and galactic as Ros2. I created a publisher from the example_interface package. And I want to subscribe it with Ros1 std_msgs package. But the error I get is as follows: with ROS 2 type 'example_interfaces/msg/Float64' and ROS 1 type '': No template specialization for the pair. Can you help me ?

![Screenshot from 2023-01-29 21-41-30](https://user-images.githubusercontent.com/99767958/215337635-ccdd0fc0-30a9-4f56-9c92-857ae558d96e.png)

**Comment by Ogunniran** [comment]
Seems it was not built properly, or maybe your workspace was not properly source, maybe you could rebuild based on the README instruction and source your bridge ws before running the script.

**Comment by mertbacaksiz** [comment]
> Seems it was not built properly, or maybe your workspace was not properly source, maybe you could rebuild based on the README instruction and source your bridge ws before running the script.


I solved it by directly installing noetic own package.
Thank you.
