### ISSUE TITLE
help wirh ros melodic and dashing bridg (it failed)

### ISSUE THREAD

**Issue by gitgeek29** [ros2/ros1_bridge#421]
clone the code https://github.com/lFatality/ros2_bridge_custom_interfaces 
         change bash to melodic and dashing 
took the dashing bridge from here https://github.com/ros2/ros1_bridge
 but bridge is not building giving following error: 

usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/unique_ptr.h:263:4: note: in instantiation of member function 'std::default_delete<ros1_bridge::ServiceFactoryInterface>::operator()' requested here
          get_deleter()(__ptr);
          ^
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/get_factory.cpp:153:44: note: in instantiation of member function 'std::unique_ptr<ros1_bridge::ServiceFactoryInterface, std::default_delete<ros1_bridge::ServiceFactoryInterface> >::~unique_ptr' requested here
  std::unique_ptr<ServiceFactoryInterface> factory;
                                           ^
1025 warnings and 2 errors generated.
make[2]: *** [CMakeFiles/ros1_bridge.dir/generated/get_factory.cpp.o] Error 1
In file included from /home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs__msg__GoalID__factories.cpp:3:
**In file included from /home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs_factories.hpp:6:
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory.hpp:213:19: error: no type named 'MessageInfo' in namespace 'rclcpp'
    const rclcpp::MessageInfo & msg_info,**
          ~~~~~~~~^
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory.hpp:142:64: error: no type named 'MessageInfo' in namespace 'rclcpp'
      void(const typename ROS2_T::SharedPtr msg, const rclcpp::MessageInfo & msg_info)> callback;
                                                       ~~~~~~~~^
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory.hpp:47:3: warning: 'create_ros1_publisher' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  create_ros1_publisher(
  ^
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs_factories.hpp:40:1: note: in instantiation of template class 'ros1_bridge::Factory<actionlib_msgs::GoalID_<std::allocator<void> >, actionlib_msgs::msg::GoalID_<std::allocator<void> > >' requested here
Factory<
^
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory_interface.hpp:50:3: note: overridden virtual function is here
  create_ros1_publisher(
  ^
In file included from /home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs__msg__GoalID__factories.cpp:3:
In file included from /home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs_factories.hpp:6:
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory.hpp:57:3: warning: 'create_ros2_publisher' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  create_ros2_publisher(
  ^
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory_interface.hpp:58:3: note: overridden virtual function is here
  create_ros2_publisher(
  ^
In file included from /home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs__msg__GoalID__factories.cpp:3:
In file included from /home/isse/ros2_bridge_custom_interfaces/bridge_ws/build/ros1_bridge/generated/actionlib_msgs_factories.hpp:6:
/home/isse/ros2_bridge_custom_interfaces/bridge_ws/src/ros1_bridge/include/ros1_bridge/factory.hpp:66:3: warning: 'create_ros2_publisher' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  create_ros2_publisher(

**Comment by sloretz** [comment]
Thank you for the bug report. Both ROS Melodic and ROS Dashing are EOL and no longer supported, so I'm going to close this issue.
