### ISSUE TITLE
ros1_bridge dashing problem

### ISSUE THREAD

**Issue by gitgeek29** [ros2/ros1_bridge#422]
I'm trying to build ros1_bridge for couldn't build it. instead getting the following error: 
![image](https://github.com/ros2/ros1_bridge/assets/94112019/28bb83c1-a9bb-446a-abf1-1905fca6789a)
Does any one of you have faced the same issue?

**Comment by fujitatomoya** [comment]
@gitgeek29 Unfortunately Dashing is already E.O.L(May 2021), could you try supported distribution instead?

see more details for https://docs.ros.org/en/rolling/Releases.html.

**Comment by sloretz** [comment]
Closing as Dashing is EOL.

**Comment by dsyddn** [comment]
static_assert is a new macro in C++11.
try to modify 'static_assert' to 'assert' included in C header <assert.h>.
(tips: modify the .em file in resource folder , which generate cpp file during buiding)
