### ISSUE TITLE
ROS2 Humble: how can I subscribe topic?

### ISSUE THREAD

**Issue by er1c-cartman** [ros2/ros1_bridge#426]
Hi. I'm using Ubuntu 22.04 ROS2 Humble to connect ubuntu 20.04 noetic.

I'm using docker for installing ubuntu 20.04 noetic, and used a bridge to communicate between ros1 and ros2 on 22.04

The problem I'm facing right now is I thought I could subscribe ros1 topics on ros2 with using bridge, but is doesn't work. And it seems it can only changes some services.

The thing I'm trying to do is run navigation simulation on ROS1 and ROS2 will get occ map from ros1, and use nav2 for navigation. So using nav2 on ros1 environment.

Is there any possible ways to subscribe occ map from ros1 to ros2?

Best regards

## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by AlejandroGarcia03** [comment]
Hey, were you able on doing so? I'm facing a similar issue trying to communicate ros-humble and ros-noetic, or is it only possible to do ros-foxy and ros-noeitc communication?
