### ISSUE TITLE
Dynamic bridge does not support bi-directional message transfer on the same topic

### ISSUE THREAD

**Issue by dhood** [ros2/ros1_bridge#47]
E.g. if you run a ROS 1 "talker", ROS 2 "listener" and a ROS 2 "talker" and ROS 1 "listener" on the same topic, the `dynamic_bridge` currently only bridges in one of the two directions at a time

**Comment by fmrico** [comment]
Using RTI Connext, I am able to to bridge in two directions at a time with that configuration.

**Comment by fmrico** [comment]
I confirm that, after fixing  ros2/rmw_fastrtps#127, ros1_bridge works correctly both using RTI Connext and  Fast-RTPS.

I recommend to close this issue.
