### ISSUE TITLE
too much console output

### ISSUE THREAD

**Issue by BrannonKing** [ros2/ros1_bridge#64]
I don't think the dynamic_bridge needs to continually spew "Passing message from ROS2 to ROS1". The message would be more useful if it included the message topic and type. However, I think we would do better to aggregate those messages and output something every five seconds saying how many of each message topic/type went which direction.

**Comment by wjwwood** [comment]
Yup, the console output of the bridge could be cleaned up a lot. I think we were waiting on the console logging that @dirk-thomas is currently waiting on. That way we can make use of throttled logging messages and stuff like that. So you get some feedback without an overwhelming amount.

I'd certainly take a pr in the meantime that either disables the output or even better makes an option to enable/disable it.

**Comment by mikaelarguedas** [comment]
this can now be addressed given that logging macros are implemented in [rcutils](https://github.com/ros2/rcutils/blob/master/resource/logging_macros.h.em)

**Comment by allenh1** [comment]
I think a `--verbose=n` option is appropriate.

**Comment by mikaelarguedas** [comment]
What does `n` refer to here ? a period in seconds ?

I think a throttled debug print would be pretty good in this scenario

**Comment by allenh1** [comment]
> What does n refer to here ? 

I was referring to some sort of debug level (sorry -- that was rather unclear), but I think that a throttled print would likely be better.

But, more general still, I don't know how necessary it is to say "publishing message from ROS _ to ROS _" every single time it publishes a message.

**Comment by dirk-thomas** [comment]
This should be addressed by #90 and #91.
