### ISSUE TITLE
Assess how much memory is needed to build the bridge

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros1_bridge#84]
Right now the bridge instructions tell to build with `-j2`. Since the bridge has been refactored to have a separate compilation unit per message package, it would be valuable to assess how much memory is needed (at most) to build a message package. We could then update the build instructions accordingly for users to decide which flag is the most adapted to their setup.

**Comment by dirk-thomas** [comment]
Does it make sense to spend time on this? The information will also get outdated over time.

I would suggest to instead mention the memory load in the readme and advice the user to specific `-jN` when needed.

**Comment by mikaelarguedas** [comment]
That's a fair point, I put the `help wanted` tag because I didnt expected us to spend time on it in the near future but could be useful if anyone in the community is interested in doing this benchmarking. I'm fine with the suggested alternative, feel free to close this and submit the corresponding PR to the readme

**Comment by dirk-thomas** [comment]
I don't mind who will be working on this. I just don't think any memory analysis will be a long term "solution".

See #85.

**Comment by mikaelarguedas** [comment]
Sounds good to me
