### ISSUE TITLE
Error executing ros bridge

### ISSUE THREAD

**Issue by sagniknitr** [ros2/ros1_bridge#92]
OS- Ubuntu 16.04
ROS 1 version - ROS Kinetic
ROS 2 version - Beta 2

Error- On running command "ros2 run ros1_bridge dynamic_bridge " getting error no executable found

![rosbridge error](https://user-images.githubusercontent.com/17951883/30418655-535918bc-9951-11e7-9136-5fb2c59f5150.PNG)

**Comment by mikaelarguedas** [comment]
Please fill out all the information requested in the issue template.

Based on your screenshot I'm guessing that you built from source. How did you build the bridge? did you follow the instructions of the [README](https://github.com/ros2/ros1_bridge#building-the-bridge-from-source)?
