### ISSUE TITLE
Log message does not contain specific information

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros1_bridge#95]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - source
- Version or commit hash:
  - master
- DDS implementation:
  - doesn't matter
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Run the dynamic bridge with at least one topic pair that matches on each side, and then observe the incorrect log message.

#### Expected behavior

The log to contain something other than `ROS1_T` or `ROS2_T`.

#### Additional information

Here's an example of the log message:

```
[INFO] [ros1_bridge]: Passing message from ROS 1 ROS1_T to ROS 2 ROS2_T (showing msg only once per type) (ros1_callback() at /home/william/ros2_ws/src/ros2/ros1_bridge/include/ros1_bridge/factory.hpp:130)
```

It's nice that we went to so much effort to limit its output rate, but the content doesn't really tell you anything (neither the type nor the topic).

I believe the use of a macro here does nothing and you'd have to use `typeid(ROS1_T).name()` instead, but that will probably be mangled too:

https://github.com/ros2/ros1_bridge/blob/3f73d9a5b27f78b2a3649d938d02b1dd945bfc40/include/ros1_bridge/factory.hpp#L129-L130

**Comment by dirk-thomas** [comment]
#96 should make the type names actually be printable. @wjwwood It would be great if you could confirm that it works in your case with the patch.
